### ISSUE TITLE
Error when launching application AssociationProxyExtensionType

### ISSUE THREAD

**Issue by Christian989898** [afourmy/eNMS#400] opened 2023-09-15 11:17 UTC
Hi,

I installed all the module in the requirement but i'm getting this error when trying to launch the app:
    from sqlalchemy.ext.associationproxy import AssociationProxyExtensionType
ImportError: cannot import name 'AssociationProxyExtensionType'

**Comment by afourmy** [comment] 2023-09-15 11:43
works fine for me with sqlalchemy 2.0.20 (latest version) ?

**Comment by Christian989898** [comment] 2023-09-15 11:44
I was with the last version then i found out this "https://stackoverflow.com/questions/75391653/importerror-cannot-import-name-association-proxy-from-sqlalchemy-ext-associa" and installed 1.4.46 but same problem

**Comment by afourmy** [comment] 2023-09-15 11:50
works fine with latest version of sqlalchemy
closing as not a bug

**Closed as completed by afourmy** 2023-09-15 11:50 UTC
